### ISSUE TITLE
[Bug] Change Sora to SORA on QR code sharing screen

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#173]
**Steps to reproduce:**
1. Open QR code screen
2. Tap Receive button
**Actual result:**
User sees: My Sora Network address to Receive:
**Expected result:**
My SORA network address to Receive:

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 ((219)) for iOS version.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1p0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--071f51b16fb643f35a23cbe8f1bd64fe6b2affd7/telegram-cloud-photo-size-2-5316990429947873605-y.jpg)
