### ISSUE TITLE
[Bug]: Infinite loader if user inputs wrong password for Sora account on import from google

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#179]
### Preconditions

User has some Sora account in google 

### Steps to reproduce

1. Choose google option fro import account
2. Enter your google account
3. Choose SORA account to import 
4. Input wrong password
5. Tap Continue

### Actual behavior

User sees infinite loader

### Expected behavior

User sees Wrong password alert

### Environment

{"label"=>"Development"}

### OS version

iOS

https://github.com/sora-xor/sora-ios/assets/17094492/a1381a83-83db-4195-96b9-b566fb18625e

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (238) for iOS version.
