### ISSUE TITLE
[Bug]: Add liquidity. Message: "Ensure you have XOR left after this transaction" is not displayed

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#181]
### Steps to reproduce

1) Select tokens. [XOR] - [another token]
2) Set 100% Xor to add liquidity

### Actual behavior

Message: "Ensure you have XOR left after this transaction" is not displayed

### Expected behavior

Message: "Ensure you have XOR left after this transaction" is displayed

### Environment

{"label"=>"Production"}

**Comment by Trezeguet1** [comment]
Verified on Dev 1.0 (239) for iOS version.

![telegram-cloud-photo-size-2-5334837260308303882-y](https://github.com/sora-xor/sora-ios/assets/51509139/7b6aaf08-291f-47ab-83e9-755cb3b68825)
