### ISSUE TITLE
[Bug]: iOS - When the user changes languages Assets icon imprinted

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#182]
### Steps to reproduce

1. Change language to Arabic

2. Change language to English

### Actual behavior

When the user changes languages, icon Assets imprinted

### Expected behavior

The icon is not imprinted

### Environment

{"label"=>"Stage"}

### Additional context

![Imprinted icon](https://github.com/sora-xor/sora-ios/assets/7602319/bc952161-5356-44b4-9eeb-816be97745d5)

**Comment by Trezeguet1** [comment]
Verified on 3.7.0.1-firebase (158).

![telegram-cloud-photo-size-2-5341544461626365224-y](https://github.com/sora-xor/sora-ios/assets/51509139/440c6322-143a-44d7-aef0-f209dae1a521)

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (244) for iOS version.

![telegram-cloud-photo-size-2-5341544461626365251-y](https://github.com/sora-xor/sora-ios/assets/51509139/6139239a-b52b-4534-88f9-d4021b53cbe7)
