### ISSUE TITLE
[Bug]: Message about the first liquidity provider doesn't disappear after changing tokens

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#183]
### Preconditions

The pool with the tokens pair not created

### Steps to reproduce

1. Select a pair of tokens ( you are the first liquidity provider)

2. Change tokens

### Actual behavior

Message about the first liquidity provider doesn't disappear 

### Expected behavior

Message about the first liquidity provider  disappear 

### Environment

{"label"=>"Stage"}

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (239) for iOS version.

There is no message already about the first liquidity provider on tokens where there are no such ones yet.

![telegram-cloud-photo-size-2-5332618505972993641-y](https://github.com/sora-xor/sora-ios/assets/51509139/9026466b-099c-4e8d-96cc-c46282034a9c)

![telegram-cloud-photo-size-2-5332618505972993642-y](https://github.com/sora-xor/sora-ios/assets/51509139/90d33481-b8b4-4d1e-afd5-e415bde413fc)
