### ISSUE TITLE
[Bug]: rewrite backup leads to clones

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#185]
### Preconditions

User has a backup of [Account 1] in Google
Account is not imported to Sora app

### Steps to reproduce

1. Go to the onboarding screen
2. Import [Account 1] by mnemonic phrase. 
3. Try to create a Google backup
4. Proceed to rewrite an existing backup
5. Forget an account
6. Tap import account from Google
7. See the list of backups

### Actual behavior

A dublicate is created.

### Expected behavior

Old backup should be deleted

### Environment

{"label"=>"Development"}

**Comment by Trezeguet1** [comment]
Verified on 1.0 (255) version. 

The backup logic is broken because it is no longer possible to backup more than one wallet and other wallets are not included in the list of wallets to import from Google.

**Comment by Trezeguet1** [comment]
The entire list of wallets is displayed on the onboarding screen, but after the first import only one wallet is shown in the Google list, it looks like this is an import problem within the application. I pinned the video to a private message.

![telegram-cloud-photo-size-2-5384552778069823438-y](https://github.com/sora-xor/sora-ios/assets/51509139/6de2b92f-201a-44ed-b1df-4aa3c3af7493)

**Comment by Trezeguet1** [comment]
Verified on 1.0.257 version.
Now after a backup it is suggested to create a new wallet every time - when you choose import from Google.

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.
