### ISSUE TITLE
[Bug]: Android - order numbers of tokens don't fit on the screen

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#186]
### Steps to reproduce

Explore tab - Currencies - Expand

### Actual behavior

Some order numbers don't fit the screen

### Expected behavior

works well

### Environment

{"label"=>"Stage"}

### Additional context

![IMG_9441](https://github.com/sora-xor/sora-ios/assets/7602319/04730451-e79d-483e-9884-aaf36560731d)

**Comment by Tieumsan** [comment]
@arvifox we might need input from @spitsynval on this from the design perspective

**Comment by Trezeguet1** [comment]
Verified on 3.7.0.1-firebase (158).
Fixed on dev side.
Tests cannot be performed until the list of assets is not complete and in the development environment there is no way to increase the list and only in the stage there are already more tokens.

![telegram-cloud-photo-size-2-5343983552078925801-y](https://github.com/sora-xor/sora-ios/assets/51509139/24d0d2cb-f5dc-4ac9-ac7c-50140ad3e954)
