### ISSUE TITLE
[Bug]: backup banner should be removed after the backup is performed

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/Sora-iOS#187]
### Steps to reproduce

1. Go to wallet tab
2. Tap backup now on the banner
3. Create a Google backup
4. Return to Wallet tab

### Actual behavior

Banner still exists

### Expected behavior

It should be removed

### Environment

{"label"=>"Development"}

**Comment by Tieumsan** [comment]
We should also add a cross to the banner. If users don't want to back up their account on Google, it's their right.

@spitsynval @arvifox

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (238) for iOS version. 

![telegram-cloud-photo-size-2-5332618505972993371-y](https://github.com/sora-xor/sora-ios/assets/51509139/47dc7d2a-6a7d-4510-945b-00a2e9274a94)

![telegram-cloud-photo-size-2-5332618505972993372-y](https://github.com/sora-xor/sora-ios/assets/51509139/41a967f2-1da7-4d66-a64c-6dddffb155b8)
