### ISSUE TITLE
[Tech]: Manage error message when user doesn't have enough space on google drive

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#188]
### Problem statement

there is no relevant message about absence of free space 

### Definition of Done

display relevant message

**Comment by Trezeguet1** [comment]
<img width="374" alt="Screenshot 2023-11-15 at 15 46 46" src="https://github.com/sora-xor/sora-ios/assets/51509139/97a84509-a883-46c2-b106-9f279a77dae3">

**Comment by Trezeguet1** [comment]
<img width="415" alt="Screenshot 2023-11-16 at 13 09 01" src="https://github.com/sora-xor/sora-ios/assets/51509139/a8bbedd2-f017-4183-b5d4-ed17b4d30c4b">
