### ISSUE TITLE
[Tech]: Investigate WebSocket implementation

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#189]
### Problem statement

People reported very slow loading time with slow internet connection or roaming. But Fearless seem to work fast enough.

### Definition of Done

- Determine the reason of very slow loading time
- Investigate implementation of WebSocket on Fearless
- Determine how to improve the implementation in the SORA wallet

**Comment by ShlyapkinIN** [comment]
result of measurements:

setupRemoteConfig started 2023-11-15 09:26:44 +0000
setupRemoteConfig finished 2023-11-15 09:27:03 +0000
loadGenesis started 2023-11-15 09:27:03 +0000
loadGenesis finished 2023-11-15 09:27:05 +0000
loadAssetsInfo started 2023-11-15 09:27:05 +0000
loadAssetsInfo finished 2023-11-15 09:27:14 +0000
throttle 2023-11-15 09:27:14 +0000
startChain started 2023-11-15 09:27:14 +0000
startChain finished 2023-11-15 09:27:14 +0000

conclusions: we need reduce time for downloading remote config
