### ISSUE TITLE
[Bug]: iOS - Liquid assets. Edit mode. Changes are applied after restart

### ISSUE THREAD

**Issue by pg-vlad** [sora-xor/Sora-iOS#192]
### Preconditions

Liquid assets. Edit mode opened

### Steps to reproduce

1. Add/Remove token to favorite
2. Return to Main screen

### Actual behavior

 Changes are applied after restart

### Expected behavior

Changer should take effect after refreshing Main page

https://github.com/sora-xor/sora-ios/assets/55486343/03ed7d2b-cd8e-40de-b72e-676ee7109dce

### Environment

{"label"=>"Stage"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (239) for iOS version.

![telegram-cloud-photo-size-2-5334870305786678793-y](https://github.com/sora-xor/sora-ios/assets/51509139/2cb1ed72-c303-4027-a3da-fc4860c9be71)
