### ISSUE TITLE
[Bug]: iOS - Some icons are missing or wrong

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#193]
Some icons we get from the whitelist are either wrong or missing (blank)

- Ternoa

- SOSHIBA

- XSTXAU

- UmiToken

If you find others, please add them to this list so that we fix them.

**Comment by ShlyapkinIN** [comment]
waiting for the update of source of icons

**Comment by spitsynval** [comment]
![CAPS](https://github.com/sora-xor/sora-ios/assets/109540030/591c191b-6425-42fe-9317-7c1b8297f3f8)
![SOSHIBA](https://github.com/sora-xor/sora-ios/assets/109540030/540c1cd4-dd44-4211-894c-d3ce9591b237)
![UMI](https://github.com/sora-xor/sora-ios/assets/109540030/6a24f0ce-be43-4f08-ba9c-df1afb8cad53)
![XSTXAU](https://github.com/sora-xor/sora-ios/assets/109540030/c47ee3e7-20aa-4a25-a67a-fcfd1b034d1c)

**Comment by spitsynval** [comment]
[Missing icons.zip](https://github.com/sora-xor/sora-ios/files/13297644/Missing.icons.zip)
