### ISSUE TITLE
[Bug]: iOS - top bar on Wallet screen changes its direction in Arabic and Hebrew after some actions

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#196]
### Preconditions
Hebrew or Arabic is set up

###  Steps to reproduce
1. Go to Wallet screen 
2. Look at the top bar
3. Make some actions (for example, go to asset details and back, then - reload the app - there are no particular actions, see the screencast)

### Actual result
At first, top bar is mirrored: QR code is on the left and Account name - on the right)
But after some actions top bar has a left-to-right direction

### Expected Result
Direction doesn't change

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (219) for iOS version.
The direction of the QR code and Account name no longer changes after changing the language.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3BvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e2f00f66070c8884a5e87830b6e551afb724f7a/telegram-cloud-photo-size-2-5312003667974541927-y.jpg)
