### ISSUE TITLE
[Bug]: iOS - back arrow should be mirrored

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#197]
### Preconditions
Arabic or Hebrew languages is set up

### Steps to reproduce
Go to Settings tab - Tap App settings - Change language

### Actual result
Back arrow looks to the left

### Expected Result
It should look to the right (and in all other places of the app). Look at the screenshot from Android

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (15) Soralution version.

This bug with the current legacy is quite difficult and dangerous to implement, so I suggest leaving it as is.
