### ISSUE TITLE
[Bug]: iOS - too much space below the show 0 balances

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#198]
There seem to be too much space below the show 0 balances

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c42e48ef36795d1d0a8eb3c6514f3a6babd097c/FILE%202023-09-27%2013_21_42.mp4)

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (219) for iOS version.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dcb57a07d9f2f96655b43d3da4cd105c09ccd36/photo_2023-10-24%2012.30.37.jpeg)
