### ISSUE TITLE
iOS - Verify lokalisation of number formatting

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#202]
### Description
We need to ensure that we take care of every detail of our UI/UX. Not only do we want our translations to be precise, but also that the number formatting is correctly adapted to the lokalisation.

Languages use a different format for displaying numbers.

### Definition of Done
The format of numbers corresponds to the active lokalisation in all places of the app

### Number formatting by lokalisation
@spitsynval to complete (either simple example, or link to Figma)

Arabic →  

Persian → 

Hebrew →

**Comment by spitsynval** [comment]
@ShlyapkinIN Sooo .. can I consider this task done?
