### ISSUE TITLE
[Bug]: XOR fiat price shows on Explore screen is 0$

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#215]
### Steps to reproduce

1. XOR price is 0.002$
2. Open Explore screen

### Actual behavior

XOR fiat price is 0$
![image](https://github.com/sora-xor/sora-ios/assets/17094492/357f5ee6-a8a6-4631-a51f-dfab5d9a42c5)

### Expected behavior

We should check we comply with the number formatting (iOS)
![image](https://github.com/sora-xor/sora-ios/assets/17094492/e645d72a-f791-45f0-a432-f2d8aac42cfb)

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (238) for iOS version.

![telegram-cloud-photo-size-2-5332618505972993384-y](https://github.com/sora-xor/sora-ios/assets/51509139/df9d4ec7-ac56-4d3f-b699-11352f4d8241)
