### ISSUE TITLE
[Bug]: iOS - UI issues after changing language

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#216]
### Preconditions

Import or create a wallet

### Steps to reproduce

1. Nav bar -> Go to the settings
2. Tap on App settings -> Language, Appearance
3. Change language

### Actual behavior

1. An additional assets icon appears on the left side of the nav bar - after changing the language (using Arabic).
2. The text App settings in the settings moves out - also after changing the currency (using Arabic), it should be centered if the direction changes.
3. A green point is applied to the first word on the sora card in the settings - after changing the language.

### Expected behavior

It is necessary to fix UI issues after changing language in the settings.

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

![telegram-cloud-photo-size-2-5312003667974541927-y](https://github.com/sora-xor/sora-ios/assets/51509139/93b11b80-94fe-4385-8bcc-79d67e596d40)

![telegram-cloud-photo-size-2-5312003667974541928-y](https://github.com/sora-xor/sora-ios/assets/51509139/b93407f4-e0d6-4725-a799-b0f115a75f8a)

![telegram-cloud-photo-size-2-5312003667974541929-y](https://github.com/sora-xor/sora-ios/assets/51509139/97783f75-10bf-4e1e-a97b-a481caff2ac8)

![telegram-cloud-photo-size-2-5312003667974541931-y](https://github.com/sora-xor/sora-ios/assets/51509139/05d5b61b-f22b-4220-ac59-8dc51f6dd485)

![telegram-cloud-photo-size-2-5312003667974541932-y](https://github.com/sora-xor/sora-ios/assets/51509139/789b0838-6220-46d6-9c7b-0f723e6f6385)

**Comment by Trezeguet1** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWF6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--150e65acffe9704c2738f25f05d5b632ab022341/telegram-cloud-photo-size-2-5357372348120026862-x.jpg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWl6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70f1749854806d108da58c7d159654058dd81b7e/telegram-cloud-photo-size-2-5357372348120026875-y.jpg)

**Comment by bauyrzhanabdi** [comment]
Arrow and text issue is caused systematically.
No cure for that

**Comment by Trezeguet1** [comment]
Verified on 1.0. (259) develop version.

We need to put a cross in another corner, for example the right one, so as not to overlap the name SORA.

<img width="147" alt="image" src="https://github.com/sora-xor/sora-ios/assets/51509139/5416b3e8-40c8-449c-991d-63ed99454399">

**Comment by Trezeguet1** [comment]
We decided to leave it as is since if we change the arrow in Arabic to the right the logic will be incorrect.
