### ISSUE TITLE
[Bug]: bad alignment in Hebrew, Arabic and Persian

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/Sora-iOS#231]
### Preconditions

1. Hebrew, Arabic or Persian language is set up
2. User is authorized
3. There is history in Activity

### Steps to reproduce

1. Open Wallet Tab
2. Open History Tab

### Actual behavior

Alignment is bad
![IMAGE 2023-10-27 13:51:24](https://github.com/sora-xor/sora-ios/assets/118749608/27086715-d110-4070-b78d-117c6e16c85e)
![IMAGE 2023-10-27 13:51:29](https://github.com/sora-xor/sora-ios/assets/118749608/85956c4a-8798-43f9-a399-9b62b5804a39)

### Expected behavior

Good alignment

### Environment

{"label"=>"Development"}

**Comment by Trezeguet1** [comment]
Verified on 1.0. (255) version. 

The text on the Activity is now aligned and the value is now displayed to the left. Now the indentation is the same as on the right.

![telegram-cloud-photo-size-2-5382341028826172893-y](https://github.com/sora-xor/sora-ios/assets/51509139/4f76fa32-8cc7-49bd-aaaa-410a100669c1)
