### ISSUE TITLE
[Bug]: bonded XOR are calculated incorrectly

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/Sora-iOS#232]
### Preconditions

1. User is authorized
2. There are 70+ XOR tokens in his wallet

### Steps to reproduce

1. Go to Settings - Invite friends & Earn
2. Tap Start inviting
3. Tap + sign

### Actual behavior

Amount of XOR to be bonded is calculated incorrectly (0)

https://github.com/sora-xor/sora-ios/assets/118749608/0ff5276b-c692-4af2-a67a-9698d3668a61

### Expected behavior

Calculations work fine

### Environment

{"label"=>"Development"}

**Comment by Trezeguet1** [comment]
Verified on Sora Dev 1.0 (238) for iOS version.

![telegram-cloud-photo-size-2-5332618505972993409-y](https://github.com/sora-xor/sora-ios/assets/51509139/3ca4d8bb-3a37-4287-b09f-6a492e7ef324)

![telegram-cloud-photo-size-2-5332618505972993410-y](https://github.com/sora-xor/sora-ios/assets/51509139/9cb0f62c-d734-46aa-8ae1-dd11ae399c97)
