### ISSUE TITLE
[Bug]: Rounded buttons are broken after dark mode switching

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#268]
### Steps to reproduce

1. Open More menu
2. Tap App settings
3. Turn on Dark mode
4. Turn off Dark mode
5. Close App settings screen

### Actual behavior

Buttons has squared shapes
https://github.com/sora-xor/sora-ios/assets/17094492/317d40ec-e05d-420b-9186-0c0cb4ac8837

### Expected behavior

Buttons has the same shapes

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on Soralution 3.7.0 (22) version.
