### ISSUE TITLE
iOS - See Pools Eligible for Staking

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#287]
As a user I want to see the pools supported by Demeter farming so that I benefit from the functionalities of the SORA ecosystem.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] redesign of Explore screen

- [x] add list of available farms
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-600

**Comment by Trezeguet1** [comment]
Verified on latest Solution version.

Acceptance criteria were checked and bugs were created within individual tasks.
