### ISSUE TITLE
iOS - Remove Stake on Pool

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#289]
As a <ins>staker on my liquidity provision</ins> I want to <ins>remove my stake on my pooled assets</ins> so that <ins>I can fully control my assets</ins>.

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-604

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.
