### ISSUE TITLE
iOS - Stake on Pool

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#291]
<p>As a <u>liquidity provider</u> I want to <u>stake my pooled assets</u> so that <u>I can get rewards from putting my assets to work for the ecosystem</u>.</p>

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-602

**Comment by arvifox** [comment]
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6624%3A41&mode=design&t=YyHeTosHjwcLNRv6-1

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (19) Soralution version.
