### ISSUE TITLE
iOS - Claim Rewards for Stake on Pool

### ISSUE THREAD

**Issue by arvifox** [sora-xor/Sora-iOS#292]
As a <ins>staker on my liquidity provision</ins> I want to <ins>claim my rewards for staking on pools</ins> so that <ins>I can get rewarded for putting my assets to work for the SORA ecosystem</ins>.

Aha! Link: https://soramitsucoltd.aha.io/features/SORANEO-606

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.
