### ISSUE TITLE
[Bug]: [Dark theme] iOS - The light mnemonic is not visible during import 

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#294]
### Preconditions

1. Select a dark theme in the system -> Select a light theme in the application
2.  Select a dark theme in the system -> Select a dark theme in the application

### Steps to reproduce

1. Import account 
2. Enter your secret Passphrase

3. Check Swap flow where the text changes color
4. Check dialogs where the text changes color

### Actual behavior

The light mnemonic is not visible during import when the light theme is selected.

![telegram-cloud-photo-size-2-5361589945875156313-y](https://github.com/sora-xor/sora-card-ios/assets/51509139/052d1c6a-71dc-49a3-bfa0-704322d5157b)

![telegram-cloud-photo-size-2-5359622112119214601-y](https://github.com/sora-xor/sora-ios/assets/51509139/710b1cb4-b17c-4380-9a5e-f674eae1e654)

### Expected behavior

The mnemonic should be shown during import if the light or dark theme is selected.

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

Version Soralution 3.7.0 (13) in TF

**Comment by 2bogd** [comment]
build: https://jenkins.soramitsu.co.jp/job/sora/job/sora-ios/view/tags/job/3.7.0/19/console

**Comment by Trezeguet1** [comment]
Verified on Soralution 3.7.0 (22) version.
