### ISSUE TITLE
[Bug]: iOS - Transaction loading status is white on dark theme in Explore tab when scrolling down

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#299]
### Preconditions

Perform a large number of transactions

### Steps to reproduce

1. Go to the Explore 
2. Scroll down 
3. Wait until data is loaded

### Actual behavior

Transaction loading status is white on dark theme in Explore tab when scrolling down.

![telegram-cloud-photo-size-2-5366255886676381378-y](https://github.com/sora-xor/sora-ios/assets/51509139/3626ccef-dfcd-433f-9241-2c41869bedc0)

### Expected behavior

Transaction loading status should match the dark theme in Explore tab when scrolling down.

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

Version TF Soralution 3.7.0 (22).

**Comment by bauyrzhanabdi** [comment]
Transaction loading is purple now as of last update
Looks like recent changes on dark mode fixed it.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b682182b1295744b1d64ba6570ef2f63363ffc6/load.jpg)

**Comment by Trezeguet1** [comment]
Verified on 1.0. (259) develop version.

![telegram-cloud-photo-size-2-5415842598368694403-y](https://github.com/sora-xor/sora-ios/assets/51509139/8ed220e5-761e-42b2-8ad4-a0c789e0f1d4)
