### ISSUE TITLE
[Bug]: Scrolling in swap screen

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#304]
<img width="360" alt="Screenshot 2023-11-15 at 14 01 27" src="https://github.com/sora-xor/sora-ios/assets/51509139/03d6cf87-a454-4f06-ba8b-7240d20e46a7">

**Comment by ShlyapkinIN** [comment]
https://github.com/sora-xor/sora-ios/assets/16333850/bdad5936-61c3-40c6-9a5b-e3e86d7284c9

**Comment by Trezeguet1** [comment]
Verified on 1.0 (255) version.

Then we need to optimize the devices on which we want to correct this logic.

Scrolling for a display higher than xxx resolution must be removed.

https://www.yalehome.com/ae/en/support/general-info-faq/ios-13-and-ipados-are-compatible-with-these-devices

![telegram-cloud-photo-size-2-5377477768637435764-y](https://github.com/sora-xor/sora-ios/assets/51509139/9bd59206-b392-4405-a0dd-2479f97c7e8c)

**Comment by Trezeguet1** [comment]
Verified on 3.8.3(13) version.
