### ISSUE TITLE
[Bug]: Dismissing scroll feature on pool details screen is disabled

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#305]

**Comment by Trezeguet1** [comment]
Verified on 1.0 (255) version.

There is no scrolling when there is not enough content.
A scroll will appear if there is more content than there is space on the screen - when something is stacked, for example on the xor val pair solution.

Matthew's problem was that he did not close a detail with a large amount of content by swiping - Now it works correctly.

![telegram-cloud-photo-size-2-5382177631090363461-y](https://github.com/sora-xor/sora-ios/assets/51509139/90204589-3e90-40c3-890e-f91fba8d89b8)

![telegram-cloud-photo-size-2-5382177631090363462-y](https://github.com/sora-xor/sora-ios/assets/51509139/7c38f204-292a-4f02-a8d1-9a9cb52c8b15)
