### ISSUE TITLE
[Bug]: iOS - There is no scrolling of wallets on the "Select account to import" screen

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#311]
### Preconditions

User has more than 8 a Google accounts

### Steps to reproduce

1. Add account
2. Import wallet
3. Google -> Select Google account
4. Try to scroll accounts 

### Actual behavior

 There is no scrolling of wallets on the "Select account to import" screen.
 The case is relevant when importing from Google Drive if there are more than 8 accounts, as in this case.
 
 
![telegram-cloud-photo-size-2-5379870181385426172-y](https://github.com/sora-xor/sora-ios/assets/51509139/5981f10d-85a6-4a69-a490-043385b7722c)

### Expected behavior

 There should be scrolling of wallets on the "Select account to import" screen.

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

1.0 (255) develop version

**Comment by bauyrzhanabdi** [comment]
Scrolling exists if there are more than 8 accounts in Google Account
https://github.com/sora-xor/sora-ios/assets/51287586/7ef206e6-a722-4b26-89c0-90ca7f66b2ce

**Comment by Trezeguet1** [comment]
Verified on 1.0. (259) develop version.
