### ISSUE TITLE
[Bug]: iOS - Crash occurs when importing mnemonic

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#312]
### Preconditions

Copy mnemonic passphrase

### Steps to reproduce

1. Add account
2. Import account
3. Enter mnemonic
4. Enter name
5. Continue

### Actual behavior

Crash occurs when importing mnemonic.

<img width="381" alt="Screenshot 2023-11-16 at 17 32 04" src="https://github.com/sora-xor/sora-ios/assets/51509139/32ad0eb7-35f9-4c61-a264-daa5ada7bd9a">

### Expected behavior

There should be no crash during importing mnemonic.

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

1.0 (255) develop version

**Comment by ShlyapkinIN** [comment]
can't reproduce

**Comment by Trezeguet1** [comment]
Verified on 1.0 (257) version.
