### ISSUE TITLE
[Bug]: iOS - The position of the error message changes after restarting the app

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#314]
### Preconditions

Go to the Import wallet screen -> Enter passphrase and Name of account

### Steps to reproduce

1. Restart the app

### Actual behavior

The position of the error message "Invalid mnemonic passphrase" changes after restarting the app.

![telegram-cloud-photo-size-2-5379885376979718787-y](https://github.com/sora-xor/sora-ios/assets/51509139/90dab901-4b04-4eea-8eee-5ecfbe7181cf)

### Expected behavior

The error message should not change position after restarting the app and should be centered.

### Environment

{"label"=>"Development"}

### OS version

16.2

### Additional context

1.0 (255) develop version

**Comment by bauyrzhanabdi** [comment]
Can't reproduce it

https://github.com/sora-xor/sora-ios/assets/51287586/922dd3e5-9225-405f-a2b3-09a730797da2

**Comment by Trezeguet1** [comment]
Verified on 1.0(266) develop version.
