### ISSUE TITLE
[Tech]: Fix fee showing according the new refactoring on Subquery 

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#326]
### Problem statement

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3daQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--913e32040e87799e456964c2c7e07198cb620909/IMG_D427BD838154-1.jpeg)

### Acceptance Criteria

1. Fees shows accurate

### Definition of Done

User sees actual fee

**Comment by Trezeguet1** [comment]
It is necessary to roll back the subquery changes related to fee and add fresh subquery logic for transactions.

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (19) Soralution version.
