### ISSUE TITLE
[Bug]: iOS - The list of wallets disappears while a new imported wallet is being loaded

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#343]
### Preconditions

User has a some wallet

### Steps to reproduce

1. Add account -> Import via mnemonic
2. Check list of wallets

### Actual behavior

The list of wallets disappears while a new imported wallet is being loaded.

![telegram-cloud-photo-size-2-5438296017377284651-y](https://github.com/sora-xor/sora-ios/assets/51509139/3c89c039-7ccd-497f-b4b1-89430977a0b8)

### Expected behavior

The current list of wallets should always be displayed. After import, the new wallet is also added to the list of wallets.

### Environment

{"label"=>"Development"}

### OS version

17.1.2

### Additional context

Soralution 3.8.0 (9) version

**Comment by ShlyapkinIN** [comment]
1.0 (265)

**Comment by Trezeguet1** [comment]
We can't verify the version 1.0 (265) develop since there is no farming there and can only be checked in Soralution and Prod.

**Comment by Trezeguet1** [comment]
Verified on 3.8.1(8) Soralution version.

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.

The repro rate is low.
