### ISSUE TITLE
[Bug]: iOS - There is no QR code cannot be decoded alert 

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#344]
### Preconditions

User has a images or incorrect QR code for Scan

### Steps to reproduce

1. Wallet screen -> Tap on Scan QR button
2. Upload from gallery wrong QR

### Actual behavior

There is no "QR code cannot be decoded" alert when scanning an incorrect code from the gallery.

![telegram-cloud-photo-size-2-5438296017377284685-y](https://github.com/sora-xor/sora-ios/assets/51509139/f7a465f9-2a52-4631-a8d0-d7fb2f61b80b)

### Expected behavior

There Sshould be "QR code cannot be decoded" alert when scanning an incorrect code from the gallery.

### Environment

{"label"=>"Development"}

### OS version

17.1.2

### Additional context

Soralution 3.8.0 (9) version

**Comment by ShlyapkinIN** [comment]
@Trezeguet1 Could you add incorect qr code?
I have tested on random qr
![photo_2024-01-17 10 59 26](https://github.com/sora-xor/sora-ios/assets/16333850/673c28ce-a2e4-4279-b88e-471c5d0f9745)

**Comment by Trezeguet1** [comment]
Verified on Soralution 3.8.1 (13) version.
@ShlyapkinIN We need to upload code from gallery.

![telegram-cloud-photo-size-2-5280698231174583272-y](https://github.com/sora-xor/sora-ios/assets/51509139/c0b6fc34-1ac5-4b4e-9fa9-ea496f5f90cf)

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (19) Soralution version.

The case is still not implemented.

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.

![telegram-cloud-photo-size-2-5298993464710649143-y](https://github.com/sora-xor/sora-ios/assets/51509139/a1cb7b77-1ea6-470c-9f96-4aa93362bc05)
