### ISSUE TITLE
[Bug]: iOS - We cannot create a custom node due to the error "This node is invalid"

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#345]
### Preconditions

Copy address of your Node wss://ws.relaychain-node-1.k1.tst.fearless.soramitsu.co.jp
or copy incorrect address wss://fajfajf.com

### Steps to reproduce

1. More -> Nodes
2. Add node -> Enter node name
3. Enter node address 
4. Submit

### Actual behavior

We cannot create a custom node due to the error "This node is invalid".
The Submit button is shown as active although a node cannot be created.

![telegram-cloud-photo-size-2-5438296017377284661-y](https://github.com/sora-xor/sora-ios/assets/51509139/c1d1c243-9b14-4edd-8d14-5a97c62ac463)

![telegram-cloud-photo-size-2-5438296017377284660-y](https://github.com/sora-xor/sora-ios/assets/51509139/25cd69ca-b9d4-446a-bb72-a129f8a36d83)

### Expected behavior

We should be able to create a custom node.
The submit button should be disabled if the node address is entered incorrectly.

### Environment

{"label"=>"Development"}

### OS version

17.1.2

### Additional context

Soralution 3.8.0 (9) version

**Comment by ShlyapkinIN** [comment]
wss://fajfajf.com - it's the correct address. I have checked in https://test.polkaswap.io/#/wallet

**Comment by ShlyapkinIN** [comment]
wss://ws.framenode-3.s2.stg1.sora2.soramitsu.co.jp - address of working node

**Comment by ShlyapkinIN** [comment]
wss://ws.relaychain-node-1.k1.tst.fearless.soramitsu.co.jp - node is off

**Comment by ShlyapkinIN** [comment]
Added loaded to determine type of error

**Comment by Trezeguet1** [comment]
Verified on Soralution 3.8.1 (13) version.

wss://ws.framenode-3.s2.stg1.sora2.soramitsu.co.jp
