### ISSUE TITLE
[Tech]: Show fiat value for the Reward asset amount on Farming #322

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#350]
### Problem statement

User sees rewards in tokens only, he doesn’t know how much it in fiat
![image](https://github.com/sora-xor/sora-ios/assets/17094492/b5cf73c2-cc88-42d7-b5c3-ea67faca523d)

### Acceptance Criteria

User has a farming rewards and he sees amount in fiat

### Definition of Done

1. Asset rewards in tokens
2. Asset rewards in fiat value

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.

![telegram-cloud-photo-size-2-5294472101098543285-y](https://github.com/sora-xor/sora-ios/assets/51509139/a7426991-714a-4d6b-b8e5-108a46a1970e)
