### ISSUE TITLE
iOS - Layout pool share selection screen

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#351]
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6624%3A655&mode=design&t=yDKLZckADbY7xl4e-1
- [x] ui
- [x] domain

**Comment by Trezeguet1** [comment]
Verified on 3.8.3(13) version.
