### ISSUE TITLE
iOS - Layout claim reward

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#352]
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6678%3A4475&mode=design&t=1eO80qltcG2dlGEG-1

- [x] ui
- [x] domain

**Comment by Trezeguet1** [comment]
Verified on 3.8.3(13) version.
