### ISSUE TITLE
[Tech]: Hide fees info on Receive transaction

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#355]
### Problem statement

Now users complain if they see fees on receive side, tx fee was paid by sender side.
![image](https://github.com/sora-xor/sora-android/assets/17094492/aa1fa90c-323b-4f93-b45b-d05fb9f4178b)

### Acceptance Criteria

1. User shouldn't sees Fee info on receive tx

### Definition of Done

User doesn't see Fee info on receive tx

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (19) Soralution version.

![telegram-cloud-photo-size-2-5294472101098543030-y](https://github.com/sora-xor/sora-ios/assets/51509139/80e5690d-2ed0-4680-b330-c4d3254e688c)
