### ISSUE TITLE
iOS - Add buttons to farm details screen

### ISSUE THREAD

**Issue by ShlyapkinIN** [sora-xor/Sora-iOS#356]
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6624%3A124&mode=design&t=1eO80qltcG2dlGEG-1

https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6624%3A86&mode=design&t=1eO80qltcG2dlGEG-1

- [x] ui
- [x] domain

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (15) Soralution version.
