### ISSUE TITLE
[Bug]: iOS - UI fixes for small detail issues

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#361]
### Preconditions

User has a pools

### Steps to reproduce

1. Go to the Wallet tab
2. Check QR code icon in the right corner
3. Go to the pool details screen
4. Swipe to up

### Actual behavior

1. Small detail (square shade around the QR code icon)
![telegram-cloud-photo-size-4-6021748452452581536-x](https://github.com/sora-xor/sora-ios/assets/51509139/d3524daa-7111-4fe7-b5ba-08aa97009340)
2. Also small detail (on top)

https://github.com/sora-xor/sora-ios/assets/51509139/c2628977-51a1-4037-ae51-b70fa2ed6488

### Expected behavior

Implement fixes for UIS issues.

### Environment

{"label"=>"Development"}

### OS version

17.1.2

### Additional context

Version 1.0 (266) develop

**Comment by ShlyapkinIN** [comment]
1. Small detail (square shade around the QR code icon) - fixed
2. It's native behaviour, if we need customization we need a layout

**Comment by Trezeguet1** [comment]
Verified on Soralution 3.8.1 (13) version.
