### ISSUE TITLE
[Bug]: iOS - items in search results on Explore page are not clickable 

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/Sora-iOS#373]
### Preconditions

A wallet is connected

### Steps to reproduce

1. Go to Explore page
2. Type "Sora" in the Search field
3. Try to tap any search item
![photo_2024-01-17 17 01 59](https://github.com/sora-xor/sora-ios/assets/118749608/0d942dda-89ce-4ed0-b1e1-c774ae3c92fa)

### Actual behavior

Items are not clickable

### Expected behavior

Details are opened

### Environment

{"label"=>"Stage"}

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (15) Soralution version.
