### ISSUE TITLE
[Bug]: iOS - there is no possibility to add a new pool on Explore page

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/Sora-iOS#374]
### Preconditions

A wallet is connected

### Steps to reproduce

1. Go to Explore tab - Pools

### Actual behavior

There is no button to add a pool
![photo_2024-01-17 17 00 37](https://github.com/sora-xor/sora-ios/assets/118749608/e5bbeb79-4450-4d54-bccf-b4c2a7b609d1)

### Expected behavior

The button exists

### Environment

{"label"=>"Stage"}

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (15) Soralution version.

![telegram-cloud-photo-size-2-5292142356218370028-y](https://github.com/sora-xor/sora-ios/assets/51509139/6f5f4546-e742-45ac-918c-f73817972034)
