### ISSUE TITLE
[Bug]: iOS - Your pool share is displayed incorrectly... as 49.56%

### ISSUE THREAD

**Issue by Trezeguet1** [sora-xor/Sora-iOS#375]
### Preconditions

1. Stake farm before it with 50%
2. Relaunch the app

### Steps to reproduce

1. Go to the Farming details
2. Check Your pool share...

### Actual behavior

Your pool share is displayed incorrectly... as 49.56%

![telegram-cloud-photo-size-2-5276326096201175685-y](https://github.com/sora-xor/sora-ios/assets/51509139/c062ee32-37e8-4a7e-afb1-486572728cbc)

### Expected behavior

Your pool share... should be displayed correctly as 50%

### Environment

{"label"=>"Development"}

### OS version

17.2.1

### Additional context

Soralution 3.8.1 (13) version

**Comment by ShlyapkinIN** [comment]
I think there is a misunderstanding about which percent will be final after staking. We should see "Your pool share stacked will be". It's the final percentage after stacking.
![photo_2024-01-18 19 50 25](https://github.com/sora-xor/sora-ios/assets/16333850/a71ea7c1-c3a0-47da-a9ce-23bfd33b40e3)

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (15) Soralution version.
