### ISSUE TITLE
[Bug]: User sees a 0 fee for add liquidity transactions in tx details

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#390]
### Preconditions

Soralution 3.8.1 (15)

### Steps to reproduce

1. Open any pool
2. Make add liquidity transaction (or swap)
3. See the fee on transaction details or open this tx from activity screen

### Actual behavior

User sees Network fee 0 xor

### Expected behavior

User sees 210 xor

### Environment

{"label"=>"Development"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.
