### ISSUE TITLE
[Bug]: Farming percents don't update if user changed it

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#392]
### Steps to reproduce

1. Open explore screen
2. Choose XSTUSD-XST (XSTUSD) farm
3. Change farming percent

### Actual behavior

User sees old percents
https://github.com/sora-xor/sora-ios/assets/17094492/a8cb9692-0b73-4631-b667-7693fe12f6a4

### Expected behavior

User sees updated percents

### Environment

{"label"=>"Stage"}

### OS version

iOS

**Comment by Trezeguet1** [comment]
Verified on 3.8.1 (20) Soralution version.

The Your pool share staked percent is changed.
