### ISSUE TITLE
[Tech]: Show tokens alphabetically when the app can't get tokens TVL

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#397]
### Problem statement

Now user sees shimmers only 
![image](https://github.com/sora-xor/sora-ios/assets/17094492/7496fbee-b9eb-48be-ad49-0c171607d293)

### Acceptance Criteria

If the app can't get a TVL's user sees tokens with prices alphabetically 

### Definition of Done

Tests with old tvl request to subquery

**Comment by Trezeguet1** [comment]
Verified on prod version.

![telegram-cloud-photo-size-2-5296501915527534838-y](https://github.com/sora-xor/sora-ios/assets/51509139/0fc4aa15-5084-4e16-9598-09e89cf7e8a7)
