### ISSUE TITLE
[Bug]: Autotests - App crashes when opening Nodes screen with Appium inspector

### ISSUE THREAD

**Issue by OlgaSamorodnova** [sora-xor/Sora-iOS#400]
### Steps to reproduce

1. Connect to Appium Inspector
2. Open simulator and go to Change Node
3. Refresh the page in Inspector

https://github.com/sora-xor/sora-ios/assets/118749608/6c5664e2-0965-4379-aaca-f657eb85d171

### Actual behavior

App crashes

### Expected behavior

We need to get locators in Nodes dialog

### Environment

{"label"=>"Development"}

**Comment by Trezeguet1** [comment]
@OlgaSamorodnova 

Ready to test
