### ISSUE TITLE
[Tech]: [iOS] Make changes into LP Fee information according new returned from quote

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/Sora-iOS#432]
### Problem statement

We have a task which will change the data of quote - https://github.com/sora-xor/sora2-network/issues/925
Design task - https://app.zenhub.com/workspaces/sora-wallet---development-6529439e287e980cb41b583b/issues/zh/22
Now we have XOR token only in LP Fee but we will have more tokens on fees for swaps.
For example for swap XST-XSTUSD we will have fee in XST.
For XOR-XSTUSD we will have 2 tokens, XOR and XST.
For XSTUSD-DAI it can be 3 tokens like XOR, XSTUSD, XST.

### Acceptance Criteria

App shows LP Fee by the asset which it receives from quote RPC.

### Definition of Done

- User sees LP Fee by the asset which it receives from quote RPC
- App can work with old and new type of RPC

**Comment by Trezeguet1** [comment]
Verified on 3.8.4(7) TF version.
